# @format

apiVersion: v1
kind: Service
metadata:
  name: node-port-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: naming-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30001
