# @format

apiVersion: v1
kind: Service
metadata:
  name: geo-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: geo-service
  ports:
    - port: 8200
      targetPort: 8200
