# @format

apiVersion: v1
kind: Service
metadata:
  name: naming-server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: naming-server
  ports:
    - port: 8761
      targetPort: 8761
