# @format

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api-gateway
  ports:
    - port: 8765
      targetPort: 8765
