# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: currency-conversion
  template:
    metadata:
      labels:
        component: currency-conversion
    spec:
      initContainers:
        - name: init-wait-for-db
          image: alpine
          command:
            [
              '/bin/sh',
              '-c',
              'for i in $(seq 1 300); do nc -zvw1 config-server-cluster-ip-service 8888 && exit 0 || sleep 3; done; exit 1'
            ]
      containers:
        - name: currency-conversion-container
          image: dipanjalmaitra/currency-conversion
          ports:
            - containerPort: 8100
          env:
            - name: ACTIVE_PROFILE
              value: default
            - name: EUREKA_URI
              value: http://naming-server-cluster-ip-service:8761/eureka
            - name: CONFIG_SERVER_URL
              value: http://config-server-cluster-ip-service:8888
