# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: geo-service
  template:
    metadata:
      labels:
        component: geo-service
    spec:
      initContainers:
        - name: init-wait-for-db
          image: alpine
          command:
            [
              '/bin/sh',
              '-c',
              'for i in $(seq 1 300); do nc -zvw1 naming-server-cluster-ip-service 8761 && exit 0 || sleep 3; done; exit 1'
            ]
      containers:
        - name: geo-service-container
          image: dipanjalmaitra/geo-service
          ports:
            - containerPort: 8200
          env:
            - name: ACTIVE_PROFILE
              value: default
            - name: EUREKA_URI
              value: http://naming-server-cluster-ip-service:8761/eureka
            - name: CONFIG_SERVER_URL
              value: http://config-server-cluster-ip-service:8888
